version: '2.1'

services:

  # Service definition for Consul cluster with a minimum of 3 nodes.
  # Nodes will use Triton CNS for the service (passed in via the CONSUL
  # env var) to find each other and bootstrap the cluster.
  consul:
    image: autopilotpattern/consul:${TAG:-latest}
    labels:
      - triton.cns.services=consul
      - com.docker.swarm.affinities=["container!=~*consul*"]
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    env_file:
      - _env
    network_mode: bridge
    command: >
      /usr/local/bin/containerpilot
